/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import dao.connectionprovider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import services.emailservice;
import services.otpgeneration;

/**
 *
 * @author Junaid Mansuri
 */
public class loginpagepassreset extends javax.swing.JFrame {

    private String OTP = "";
    private String usernewps = "";
    private String Email = "";
    private int uid=0;

    /**
     * Creates new form loginpagepassreset
     */
    public loginpagepassreset() {
        initComponents();
        setLocationRelativeTo(null);
        txtnewps.setEnabled(false);
        lblnew.setEnabled(false);
        btnreset.setEnabled(false);
        btnverify.setEnabled(false);
        lblotp.setEnabled(false);
        txtotp.setEnabled(false);

        otpgeneration og = new otpgeneration();
        OTP = og.generateotp(6);

    }

    private int throwuserid(){
        int id=0;
    try {
        
            Connection con = connectionprovider.getCon();
            PreparedStatement pst = con.prepareStatement("select userid from usertbl where usergmail=?");
            pst.setString(1, Email);
            ResultSet rs=pst.executeQuery();
            if(rs.next()){
            id=rs.getInt("userid");
            }
        } catch (NumberFormatException np) {
            JOptionPane.showMessageDialog(null, "Please Enter Password in correct Format !");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "An Error Occurred ! Please Try Again Later ");

        }
       return id;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtmail = new javax.swing.JTextField();
        btnsend = new javax.swing.JButton();
        lblmail = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblwrongps = new javax.swing.JLabel();
        lblnew = new javax.swing.JLabel();
        txtnewps = new javax.swing.JTextField();
        btnreset = new javax.swing.JButton();
        lblotp = new javax.swing.JLabel();
        txtotp = new javax.swing.JTextField();
        btnverify = new javax.swing.JButton();
        lblms = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        btnsend.setText("Send code");
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });

        lblmail.setText("Your Email");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Recover password");

        lblwrongps.setForeground(new java.awt.Color(255, 0, 0));

        lblnew.setText("New Password");

        btnreset.setText("Confirm Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        lblotp.setText("Enter OTP :");

        btnverify.setText("Verify");
        btnverify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverifyActionPerformed(evt);
            }
        });

        lblms.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lblmail)
                        .addGap(40, 40, 40)
                        .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(lblwrongps))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(540, 540, 540)
                        .addComponent(btnsend))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lblotp)
                        .addGap(33, 33, 33)
                        .addComponent(txtotp, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(lblms))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(570, 570, 570)
                        .addComponent(btnverify))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblnew)
                        .addGap(36, 36, 36)
                        .addComponent(txtnewps, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(520, 520, 520)
                        .addComponent(btnreset)))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblmail))
                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(lblwrongps)
                .addGap(8, 8, 8)
                .addComponent(btnsend)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblotp)
                    .addComponent(txtotp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(lblms)
                .addGap(3, 3, 3)
                .addComponent(btnverify)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnew)
                    .addComponent(txtnewps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(btnreset)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
        // TODO add your handling code here:
        Email = txtmail.getText().trim();

        if (Email.equals("") || !Email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
            lblwrongps.setText("Invalid Email ! Please Enter a Valid Email Address ");

        } else {

            try {

                emailservice es = new emailservice();
                es.sendOTP(Email, OTP);
                txtmail.setEnabled(false);
                lblmail.setEnabled(false);
                btnsend.setEnabled(false);
                btnverify.setEnabled(true);
                lblotp.setEnabled(true);
                txtotp.setEnabled(true);
                uid=throwuserid();
            } catch (NumberFormatException np) {
                JOptionPane.showMessageDialog(null, "Please Enter Password in correct Format !");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "An Error Occurred Please Try Again Later !");

            }
        }
    }//GEN-LAST:event_btnsendActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        usernewps = txtnewps.getText().trim().toString();
        try {
            Connection con = connectionprovider.getCon();
            PreparedStatement pst = con.prepareStatement("update usertbl set userps=? where userid=?");
            pst.setString(1,usernewps); 
            pst.setInt(2, uid);
            pst.executeQuery();
        } catch (NumberFormatException np) {
            JOptionPane.showMessageDialog(null, "Please Enter Password in correct Format !");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "An Error Occurred ! Please Try Again Later ");
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnresetActionPerformed

    private void btnverifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverifyActionPerformed
        // TODO add your handling code here:
        String user_enter_otp = txtotp.getText().trim();

        if (!user_enter_otp.equals(OTP) || user_enter_otp.equals("")) {
            lblms.setText("Invalid Otp !");
        } else {

            txtnewps.setEnabled(true);
            lblnew.setEnabled(true);
            btnreset.setEnabled(true);

            btnverify.setEnabled(false);
            lblotp.setEnabled(false);
            txtotp.setEnabled(false);

        }
    }//GEN-LAST:event_btnverifyActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
         lblms.setText("");
        lblnew.setText("");
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginpagepassreset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginpagepassreset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginpagepassreset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginpagepassreset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginpagepassreset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsend;
    private javax.swing.JButton btnverify;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblmail;
    private javax.swing.JLabel lblms;
    private javax.swing.JLabel lblnew;
    private javax.swing.JLabel lblotp;
    private javax.swing.JLabel lblwrongps;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtnewps;
    private javax.swing.JTextField txtotp;
    // End of variables declaration//GEN-END:variables
}
