/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import dao.connectionprovider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Junaid Mansuri
 */
public class viewcategory extends javax.swing.JFrame {

    private int cid = 0;
    private int nid = 0;

    /**
     * Creates new form viewcategory
     */
    public viewcategory() {
        initComponents();
        setLocationRelativeTo(null);
        loadid();
        loadtable();

    }

    private void loadid() {

        TableColumnModel tcm = tblnote.getColumnModel();
        tcm.removeColumn(tcm.getColumn(0));

        TableColumnModel tcm1 = tblcategory.getColumnModel();
        tcm1.removeColumn(tcm1.getColumn(0));

    }

    private boolean emptytable() {

        if (tblcategory.getRowCount() == 0 || tblnote.getRowCount() == 0) {

            return false;
        } else {
            return true;
        }
    }

    private void loadtable() {

        DefaultTableModel model = (DefaultTableModel) tblnote.getModel();
        model.setRowCount(0);

        try {
            Connection con = connectionprovider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from tblnote where privkey=0");
            while (rs.next()) {

                model.addRow(new Object[]{rs.getInt("noteid"), rs.getString("notetitle"), rs.getString("notecontent"), rs.getString("notedatetime")});
                 
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        DefaultTableModel cmodel = (DefaultTableModel) tblcategory.getModel();
        cmodel.setRowCount(0);
        try {
            Connection con = connectionprovider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from tblcategory");

            while (rs.next()) {

                cmodel.addRow(new Object[]{rs.getInt("categoryid"), rs.getString("categoryname")});

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        tblnote.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcategory = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblnote = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        lblcategory = new javax.swing.JLabel();
        lblnote = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblcontent = new javax.swing.JLabel();
        lbldt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnprivate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Add Category ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 13, -1, -1));

        tblcategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Categoryname"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblcategory.getTableHeader().setReorderingAllowed(false);
        tblcategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcategory);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 430));

        tblnote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Content", "Date-Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblnote.getTableHeader().setReorderingAllowed(false);
        tblnote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblnoteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblnote);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 500, -1));

        btnadd.setText("Add category");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, -1, -1));

        lblcategory.setText("Category :");
        getContentPane().add(lblcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 593, -1, -1));
        getContentPane().add(lblnote, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 580, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Select Category");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Select note to add");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, -1));

        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 670, -1, -1));
        getContentPane().add(lblcontent, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 610, -1, -1));
        getContentPane().add(lbldt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, -1, -1));

        jLabel4.setText("Note :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, -1, -1));

        jLabel5.setText("Content :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 610, -1, -1));

        jLabel6.setText("Date Time :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 640, -1, -1));

        btnprivate.setText("Make Private");
        btnprivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprivateActionPerformed(evt);
            }
        });
        getContentPane().add(btnprivate, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 590, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:

        loadtable();
        if (!emptytable()) {
            JOptionPane.showMessageDialog(null, " Note Or Category Not Found !");
            setVisible(false);
        }
    }//GEN-LAST:event_formComponentShown

    private void tblcategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcategoryMouseClicked
        // TODO add your handling code here:

        int index = tblcategory.getSelectedRow();
        TableModel model = tblcategory.getModel();
        cid = Integer.parseInt(model.getValueAt(index, 0).toString());

        String cname = model.getValueAt(index, 1).toString();
        lblcategory.setText(cname);


    }//GEN-LAST:event_tblcategoryMouseClicked

    private void tblnoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblnoteMouseClicked
        // TODO add your handling code here:
        int index = tblnote.getSelectedRow();
        TableModel model = tblnote.getModel();

        nid = Integer.parseInt(model.getValueAt(index, 0).toString());

        String title = model.getValueAt(index, 1).toString();

        String content = (String) model.getValueAt(index, 2);

        String datetime = (String) model.getValueAt(index, 3);
        lblnote.setText(title);
        lblcontent.setText(content.substring(0, 6) + "....");
        lbldt.setText(datetime);

    }//GEN-LAST:event_tblnoteMouseClicked

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        int[] selectedRow = tblnote.getSelectedRows();
        Object category = tblcategory.getSelectedRow();
        if (tblcategory.getSelectedRowCount() == 0 || tblnote.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Add Category or Note First ! ");

        } else {

            try {

                Connection con = connectionprovider.getCon();
                PreparedStatement pst = con.prepareStatement("update tblnote set categoryfk=? where noteid=?");
                for (int data : selectedRow) {
                    pst.setInt(1, cid);
                    pst.setInt(2, data + 1);
                    pst.executeUpdate();
                }
                JOptionPane.showMessageDialog(null, "Note Added To Category ");

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, "An Error occured while adding note !");
            }
            loadtable();
            lblnote.setText("");
            lblcategory.setText("");
            lblcontent.setText("");
            lbldt.setText("");
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        tblnote.clearSelection();
        tblcategory.clearSelection();
        lblnote.setText("");
        lblcategory.setText("");
        lblcontent.setText("");
        lbldt.setText("");

    }//GEN-LAST:event_formMouseClicked

    private void btnprivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprivateActionPerformed
        // TODO add your handling code here:
       DefaultTableModel model=(DefaultTableModel) tblnote.getModel();
       int row = tblnote.getSelectedRow();
       
        
        try {
            if(row == -1){
                        JOptionPane.showMessageDialog(null, "Please Select a Note To Add !");
                        return;
            }
            int[] multiplenote=tblnote.getSelectedRows();
            Connection con = connectionprovider.getCon();
            PreparedStatement pst = con.prepareStatement("update tblnote set privkey=? where noteid=?");
            for(int i=0;i<=multiplenote.length;i++){
            pst.setInt(1, 1);
            pst.setInt(2,nid);
            }
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Note Made Private Successfully ");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Making private note ");

        }
        
        loadtable();
        tblnote.clearSelection();
        tblcategory.clearSelection();
        lblnote.setText("");
        lblcategory.setText("");
        lblcontent.setText("");
        lbldt.setText("");
        
    }//GEN-LAST:event_btnprivateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewcategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewcategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewcategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewcategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewcategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnprivate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblcategory;
    private javax.swing.JLabel lblcontent;
    private javax.swing.JLabel lbldt;
    private javax.swing.JLabel lblnote;
    private javax.swing.JTable tblcategory;
    private javax.swing.JTable tblnote;
    // End of variables declaration//GEN-END:variables
}
